/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core'
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching'
import { registerRoute, NavigationRoute } from 'workbox-routing'
import { StaleWhileRevalidate, NetworkFirst } from 'workbox-strategies'
import { ExpirationPlugin } from 'workbox-expiration'

declare let self: ServiceWorkerGlobalScope

self.skipWaiting()
clientsClaim()

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// SPA routing: return index.html for all navigation requests
const handler = createHandlerBoundToURL('/index.html')
const navigationRoute = new NavigationRoute(handler, {
  denylist: [/^\/api\//],
})
registerRoute(navigationRoute)

// Runtime caching (ported from previous generateSW config)
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/v1/schedule'),
  new StaleWhileRevalidate({
    cacheName: 'flowday-schedule',
    plugins: [new ExpirationPlugin({ maxAgeSeconds: 60 * 60 * 24 })],
  })
)

registerRoute(
  ({ url }) => url.pathname.startsWith('/api/v1/assignments'),
  new NetworkFirst({
    cacheName: 'flowday-assignments',
    networkTimeoutSeconds: 5,
    plugins: [new ExpirationPlugin({ maxAgeSeconds: 60 * 5 })],
  })
)

registerRoute(
  ({ url }) => url.pathname.startsWith('/api/v1/clients'),
  new StaleWhileRevalidate({
    cacheName: 'flowday-clients',
    plugins: [new ExpirationPlugin({ maxAgeSeconds: 60 * 60 })],
  })
)

interface CustomNotificationOptions extends NotificationOptions {
  vibrate?: number[];
}

// Handle Web Push Events
self.addEventListener('push', (event) => {
  if (!event.data) return

  try {
    const data = event.data.json()
    const options: CustomNotificationOptions = {
      body: data.body,
      icon: '/icons-192.png',
      badge: '/favicon.svg',
      vibrate: [100, 50, 100],
      data: {
        url: data.url || '/',
      },
    }

    event.waitUntil(
      self.registration.showNotification(data.title, options)
    )
  } catch (err) {
    console.error('Error handling push event', err)
  }
})

// Handle Notification Clicks
self.addEventListener('notificationclick', (event) => {
  event.notification.close()

  const urlToOpen = event.notification.data.url

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // Check if there is already a window/tab open with the target URL
      for (let i = 0; i < windowClients.length; i++) {
        const client = windowClients[i]
        if (client.url === urlToOpen && 'focus' in client) {
          return client.focus()
        }
      }
      // If not, open a new window/tab
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen)
      }
    })
  )
})
